version: '3.8'

services:
  web:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./server:/app
      - media_volume:/app/media
    environment:
      - DEBUG=1
      - SECRET_KEY=your-secret-key-here
      - ALLOWED_HOSTS=*
    depends_on:
      - db
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             python manage.py runserver 0.0.0.0:8000"

  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:8000
    depends_on:
      - web
    command: npm run dev -- --host

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=shop_db
      - POSTGRES_USER=shop_user
      - POSTGRES_PASSWORD=shop_password

volumes:
  postgres_data:
  media_volume:
