#!/bin/bash

echo "🚀 KFL Deployment Token Helper"
echo "================================"
echo ""

echo "📋 Follow these steps to get your deployment tokens:"
echo ""

echo "🔵 VERCEL TOKENS:"
echo "1. Go to: https://vercel.com/account/tokens"
echo "2. Click 'Create Token'"
echo "3. Name: 'KFL Deployment'"
echo "4. Copy the token"
echo "5. Go to: https://vercel.com/teams/[your-team]/settings"
echo "6. Copy 'Team ID' (this is your ORG_ID)"
echo "7. Go to your project settings"
echo "8. Copy 'Project ID'"
echo ""

echo "🟢 NETLIFY TOKENS:"
echo "1. Go to: https://app.netlify.com/user/applications#personal-access-tokens"
echo "2. Click 'New access token'"
echo "3. Name: 'KFL Deployment'"
echo "4. Copy the token"
echo "5. Go to your site settings"
echo "6. Copy 'Site ID'"
echo ""

echo "🟡 RAILWAY TOKENS:"
echo "1. Go to: https://railway.app/account/tokens"
echo "2. Click 'New Token'"
echo "3. Name: 'KFL Deployment'"
echo "4. Copy the token"
echo "5. Go to your project settings"
echo "6. Copy 'Service ID'"
echo ""

echo "📝 ADD TO GITHUB SECRETS:"
echo "1. Go to: https://github.com/Ram-91779030/KFL/settings/secrets/actions"
echo "2. Click 'New repository secret'"
echo "3. Add each token with these names:"
echo "   - VERCEL_TOKEN"
echo "   - VERCEL_ORG_ID"
echo "   - VERCEL_PROJECT_ID"
echo "   - NETLIFY_AUTH_TOKEN"
echo "   - NETLIFY_SITE_ID"
echo "   - RAILWAY_TOKEN"
echo "   - RAILWAY_SERVICE_ID"
echo ""

echo "🎯 QUICK DEPLOY (No tokens needed):"
echo "1. Vercel: https://vercel.com/new (import KFL repo)"
echo "2. Netlify: https://app.netlify.com/start (import KFL repo)"
echo "3. Railway: https://railway.app/new (import KFL repo)"
echo ""

echo "✅ After manual deployment, your sites will be live!"
echo "🌐 Frontend: https://kfl-karshakfoodlife.vercel.app"
echo "🔧 Backend: https://kfl-backend.railway.app"
echo "📊 Admin: https://kfl-backend.railway.app/admin"
