services:
  # Frontend Service (React + Vite)
  - type: web
    name: kfl-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./build
    routes:
      - type: rewrite
        source: /api/*
        destination: https://kfl-backend.onrender.com/api/*
      - type: rewrite
        source: /*
        destination: /index.html
    headers:
      - path: /assets/*
        name: Cache-Control
        value: public, max-age=31536000, immutable
      - path: /*
        name: X-Frame-Options
        value: DENY
      - path: /*
        name: X-Content-Type-Options
        value: nosniff

  # Backend Service (Python API)
  - type: web
    name: kfl-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python api/simple.py
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: NODE_ENV
        value: production
